version: '3'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: intrinsic-learning-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: intrinsic_learning
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - intrinsic-network

  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: intrinsic-learning-backend
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/intrinsic_learning?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FRONTEND_URL=https://intrinsic-learning.ai
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - intrinsic-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: intrinsic-learning-frontend
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.intrinsic-learning.ai
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - intrinsic-network

  # Nginx service for reverse proxy
  nginx:
    image: nginx:latest
    container_name: intrinsic-learning-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infrastructure/nginx/conf.d:/etc/nginx/conf.d
      - ./infrastructure/certbot/conf:/etc/letsencrypt
      - ./infrastructure/certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - intrinsic-network

  # Certbot service for SSL certificates
  certbot:
    image: certbot/certbot
    container_name: intrinsic-learning-certbot
    volumes:
      - ./infrastructure/certbot/conf:/etc/letsencrypt
      - ./infrastructure/certbot/www:/var/www/certbot
    depends_on:
      - nginx

volumes:
  mongodb_data:

networks:
  intrinsic-network:
    driver: bridge
